---
#roles:
#  # Install a role from Ansible Galaxy.
#  - name: geerlingguy.java
#    version: 1.9.6

collections:
  # Install a collection from Ansible Galaxy.
  # for modprobe
  - name: community.general
    version: 2.5.1

  # for sysctl flags
  - name: ansible.posix
    version: 1.2.0
